---

- hosts: elkserver
  gather_facts: yes

  vars_files:
  - vars/main.yml

  roles:
    - geerlingguy.java
    - geerlingguy.nginx
    - geerlingguy.elasticsearch
    - stanley.kibana
    - geerlingguy.logstash
    - stanley.logstash-filebeat

