- name: test
  hosts: localhost         # 请加上/etc/ansible/hosts加上
  gather_facts: False      # localhost ansible_connection=local
  tasks:

    - name: echo pongpong
      echo: args="{{ args }}"
      register: res
    - debug: var=res

