---
# task file for postgresql

- name: "PostgreSQL | Create database"
  postgresql_db: name={{ proxy_dbname }}
                 state=present
  sudo_user: postgres
  when: zabbix_database_creation

- name: "PostgreSQL | Create database user"
  postgresql_user: db={{ proxy_dbname }}
                    name={{ proxy_dbuser }}
                    password={{ proxy_dbpassword }}
                    priv=ALL
                    state=present
  sudo_user: postgres
  when: zabbix_database_creation

- name: "PostgreSQL | Importing schema file"
  shell: "cd {{ datafiles_path }} && psql -h '{{ proxy_dbhost }}' -U '{{ proxy_dbuser }}' -d '{{ proxy_dbname }}' -f schema.sql && touch /etc/zabbix/schema.done"
  args:
    creates: /etc/zabbix/schema.done
  environment:
    PGPASSWORD: '{{ server_dbpassword }}'
  when: zabbix_database_creation
