---
# These tasks are responsible for copying the latest dev/production code from
# the version control system. 

- name: link file {{ project }}
  file: src={{ package_dir }}{{ project }}-release-{{ git_commit }}/{{ flag }}-{{ project }} dest={{ project_dir }}{{ flag }}-{{ project }}  owner=www group=www state=link

