---
- hosts: all
  sudo: yes

  tasks:
   - name: "Install Apache."
     yum: name={{ item }} state=present
     with_items:
         - httpd
         - httpd-devel
   - name: "Copy Configuraton file."
     copy:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
       owner: root
       group: root
       mode: 0644
     with_items:
       - {
           src: "/tmp/httpd.conf",
           dest: "/etc/httpd/conf/httpd.conf" }
       - {
           src: "/tmp/httpd-vhosts.conf",
       dest: "/etc/httpd/conf/httpd-vhosts.conf"
         }
   - name: "Make sure Apache is started and configure it to run at boot."
     service: name=httpd state=started enabled=yes

