---
- hosts: all

  vars_files:
    - vars.yml

  handlers:
    - name: restart tomcat
      command: >
        initctl restart tomcat

    - name: Install JDK.
      copy: "src={{ item.src }} dest={{ item.dest }}"
      with_items:
        - src: "./jdk-8u11-linux-x64.tar.gz"
          dest: "/tmp/"
       
        - src: "./java.sh"
          dest: "/etc/profile.d/"

    - name: Create JAVA directory
      command: >
        mkdir -p /opt/java

    - name: expand JDK.
      command: >
        tar -C /opt/java -xvf {{ download_dir}}/jdk-8u11-linux-x64.tar.gz --strip-components=1
   
    - name: Update alternatives for java.
      command: >
        update-alternatives --install /usr/bin/java java /opt/java/bin/java 300

    - name: Update alternatives for javac.
      command: >
        update-alternatives --install /usr/bin/javac javac /opt/java/bin/javac 300

    - name: Create Tomcat directory
      command: >
        mkdir -p {{ tomcat_dir }}

    - name: Add Tomcat user
      user: "name=tomcat shell=/sbin/nologin"

    - name: Download Tomcat.
      get_url:
        url: "http://apache.fayea.com/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version}}.tar.gz"
        dest: "{{ download_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Expand Tomcat.
      command: >
        tar -C {{ tomcat_dir}} -xvf {{ download_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz --strip-components=1
        creates={{ tomcat_dir }}/conf/server.xml

    - name: Rload Upstart Configuration
      command: initctl reload-configuration

    - name: Transfer Upstart Configuration of Tomcat. 
      copy: "src=./tomcat.conf  dest=/etc/init/tomcat.conf"
      notify: restart tomcat

    - name: Download Solr.
      get_url:
        url: "http://apache.fayea.com/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"

    - name: Move Solr into place
      command: >
        mkdir -p {{ solr_dir }}

    - name: Expand Solr.
      command: >
        tar -C {{ solr_dir }} -xvzf {{ download_dir }}/solr-{{ solr_version }}.tgz --strip-components=1
        creates={{ solr_dir }}/dist/solr-core-{{ solr_version }}.jar

    - name: Move Solr into place
      command: >
        mkdir -p {{ tomcat_dir }}/webapps/solr/WEB-INF/classes

    - name: Move Solr components into place.
      shell: >
        rsync -av {{ item.src }} {{ item.dest }}
        creates={{ item.creates }}
      with_items:
        - src: "{{ solr_dir }}/server/solr-webapp/webapp/*"
          dest: "{{ tomcat_dir }}/webapps/solr"
          creates: "/opt/tomcat/webapps/solr/index.html"
 
        - src: "{{ solr_dir }}/server/lib/ext/*"
          dest: "{{ tomcat_dir }}/webapps/solr/WEB-INF/lib/"
          creates: "/opt/tomcat/webapps/solr/WEB-INF/lib/slf4j-api-1.7.7.jar"

        - src: "{{ solr_dir }}/server/resources/log4j.properties"
          dest: "{{ tomcat_dir }}/webapps/solr/WEB-INF/classes/"
          creates: "/opt/tomcat/webapps/solr/WEB-INF/classes/log4j.properties"

    - name: Overwrite Solr configure file
      copy: "src=./web.xml dest=/opt/tomcat/webapps/solr/WEB-INF/web.xml"

    - name: Changem permission
      file:
        path: "/opt"
        owner: tomcat
        group: tomcat
        recurse: yes
      notify: restart tomcat
